# -*- coding: utf-8 -*-
# Generated by Django 6.0.3 on 2026-03-10 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'CategorÃ\xada',
                'verbose_name_plural': 'CategorÃ\xadas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('simbolo', models.CharField(max_length=10, unique=True, verbose_name='SÃ\xadmbolo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='CÃ³digo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('stock_actual', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Stock Actual')),
                ('costo_promedio', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Costo Promedio')),
                ('es_materia_prima', models.BooleanField(default=False, verbose_name='Es Materia Prima')),
                ('es_producto_terminado', models.BooleanField(default=False, verbose_name='Es Producto Terminado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.categoria', verbose_name='CategorÃ\xada')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.unidadmedida', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Costo Unitario')),
                ('referencia', models.CharField(max_length=50, verbose_name='Referencia')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
