# Generated by Django 6.0.3 on 2026-03-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_alter_categoria_options_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peso_unitario_kg',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Peso Unitario (kg)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Precio de Venta (Ref)'),
        ),
    ]
