# Generated by Django 6.0.3 on 2026-03-14 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_producto_peso_unitario_kg_producto_precio_venta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_materia_prima_base',
            field=models.BooleanField(default=False, help_text='Marcar para leche vaca y búfala. Precio ponderado del dashboard.', verbose_name='Materia Prima Base (leche)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Stock Máximo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Stock Mínimo'),
        ),
        migrations.CreateModel(
            name='CambioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField()),
                ('valor_nuevo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('fecha_propuesta', models.DateTimeField(auto_now_add=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_aprobados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_pendientes', to='almacen.producto')),
                ('propuesto_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_propuestos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de Producto',
                'verbose_name_plural': 'Cambios de Producto',
            },
        ),
    ]
