# Generated by Django 6.0.3 on 2026-03-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_producto_es_materia_prima_base_producto_stock_maximo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='chk_almacen_producto_stock_no_negativo'),
        ),
    ]
