# Generated by Django 6.0.3 on 2026-03-13 18:01

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0003_movimientotesoreria'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socio',
            options={'ordering': ['nombre'], 'verbose_name': 'Socio', 'verbose_name_plural': 'Socios'},
        ),
        migrations.AlterField(
            model_name='socio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='rif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RIF'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='PrestamoPorSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('monto_principal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Principal')),
                ('moneda', models.CharField(choices=[('USD', 'USD - Dólar Americano'), ('VES', 'VES - Bolívar Soberano')], default='USD', max_length=3, verbose_name='Moneda')),
                ('tasa_cambio', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, verbose_name='Tasa de Cambio (VES/USD)')),
                ('monto_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='Monto en USD')),
                ('fecha_prestamo', models.DateField(verbose_name='Fecha del Préstamo')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_recibidos', to='bancos.cuentabancaria', verbose_name='Cuenta Destino')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='socios.socio', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Préstamo por Socio',
                'verbose_name_plural': 'Préstamos por Socio',
                'ordering': ['-fecha_prestamo', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='PagoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('USD', 'USD - Dólar Americano'), ('VES', 'VES - Bolívar Soberano')], default='USD', max_length=3, verbose_name='Moneda')),
                ('tasa_cambio', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, verbose_name='Tasa de Cambio (VES/USD)')),
                ('monto_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='Monto en USD')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de Pago')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('cuenta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_prestamo', to='bancos.cuentabancaria', verbose_name='Cuenta Origen')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='socios.prestamoporsocio', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Pago de Préstamo',
                'verbose_name_plural': 'Pagos de Préstamos',
                'ordering': ['-fecha', 'id'],
            },
        ),
    ]
