# -*- coding: utf-8 -*-
# Generated by Django 6.0.3 on 2026-03-10 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Origen')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar'), ('CAMBIO_ESTADO', 'Cambio de Estado')], max_length=20, verbose_name='Acción')),
                ('entidad', models.CharField(max_length=100, verbose_name='Entidad')),
                ('entidad_id', models.PositiveIntegerField(verbose_name='ID de Entidad')),
                ('before_data', models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores')),
                ('after_data', models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
