# Generated by Django 6.0.3 on 2026-03-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=6, unique=True, verbose_name='Tipo de Documento')),
                ('ultimo_numero', models.PositiveIntegerField(default=0, verbose_name='Último Número')),
                ('prefijo', models.CharField(max_length=10, verbose_name='Prefijo')),
                ('digitos', models.PositiveSmallIntegerField(default=4, verbose_name='Dígitos')),
            ],
            options={
                'verbose_name': 'Secuencia',
                'verbose_name_plural': 'Secuencias',
            },
        ),
    ]
