# Generated by Django 6.0.3 on 2026-03-11 13:30

from django.db import migrations

from django.core.management import call_command

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'fixtures/secuencias.json')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_secuencia'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
