# Generated by Django 6.0.3 on 2026-03-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracionempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tasa', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fuente', models.CharField(choices=[('BCV_AUTO', 'BCV Auto'), ('BCV_MANUAL', 'BCV Manual'), ('USUARIO', 'Usuario')], default='BCV_AUTO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contexto', models.CharField(choices=[('FACTURA', 'Factura'), ('TESORERIA', 'Tesorería')], max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='core.categoriagasto')),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gasto',
                'unique_together': {('nombre', 'contexto')},
            },
        ),
    ]
