# Generated by Django 6.0.3 on 2026-03-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tasacambio_categoriagasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CXC_VENCIENDO', 'CxC Venciendo'), ('STOCK_MINIMO', 'Stock Mínimo'), ('TASA_NO_CARGADA', 'Tasa BCV No Cargada'), ('PRESTAMO_VENCIENDO', 'Préstamo Venciendo')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('entidad', models.CharField(max_length=100)),
                ('entidad_id', models.PositiveIntegerField()),
                ('fecha_referencia', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'unique_together': {('tipo', 'entidad', 'entidad_id')},
            },
        ),
    ]
