# Generated by Django 6.0.3 on 2026-03-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='fecha_venta_abierta',
            field=models.BooleanField(default=False, help_text='Si True: usuario ingresa fecha. Si False: fecha del SO al emitir.', verbose_name='Fecha de venta editable'),
        ),
    ]
