# Generated by Django 4.2.11 on 2026-04-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracionempresa_fecha_venta_abierta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='permitir_editar_fecha_orden_produccion',
            field=models.BooleanField(default=False, help_text='Si está activo, permite editar fecha_apertura en Orden de Producción.', verbose_name='Fecha de OP editable'),
        ),
    ]
