# -*- coding: utf-8 -*-
# Generated by Django 6.0.3 on 2026-03-10 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número de Orden')),
                ('fecha_apertura', models.DateField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=15, verbose_name='Estado')),
                ('cantidad_producida', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Cantidad Producida')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='Costo Total (USD)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-fecha_apertura', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Cantidad Consumida')),
                ('costo_unitario', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Costo Unitario (USD)')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='Subtotal (USD)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.producto', verbose_name='Producto (Materia Prima)')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.unidadmedida', verbose_name='Unidad de Medida')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='produccion.ordenproduccion', verbose_name='Orden de Producción')),
            ],
            options={
                'verbose_name': 'Consumo de Orden de Producción',
                'verbose_name_plural': 'Consumos de Orden de Producción',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rendimiento_esperado', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rendimiento Esperado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.producto', verbose_name='Producto Terminado')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.receta', verbose_name='Receta'),
        ),
        migrations.CreateModel(
            name='RecetaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_base', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Cantidad Base')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.producto', verbose_name='Materia Prima')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.receta', verbose_name='Receta')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.unidadmedida', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Detalle de Receta',
                'verbose_name_plural': 'Detalles de Receta',
                'ordering': ['id'],
            },
        ),
    ]
