# Generated by Django 6.0.3 on 2026-03-11 02:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoop',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, verbose_name='Costo Unitario (USD)'),
        ),
        migrations.AlterField(
            model_name='consumoop',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18, verbose_name='Subtotal (USD)'),
        ),
    ]
