# Generated by Django 6.0.3 on 2026-03-11 21:48

from django.db import migrations


def verificar_ordenes_abiertas(apps, schema_editor):
    OrdenProduccion = apps.get_model("produccion", "OrdenProduccion")
    if OrdenProduccion.objects.filter(estado="ABIERTA").exists():
        raise ValueError("Existen Órdenes de Producción en estado ABIERTA. Debe cerrarlas o anularlas antes de ejecutar esta migración destructiva (eliminar campos). Se recomienda hacer pg_dump previo.")

class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_consumoop_default_costo_subtotal'),
    ]

    operations = [
        migrations.RunPython(verificar_ordenes_abiertas),
    ]
