# Generated by Django 6.0.3 on 2026-03-11 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_producto_peso_unitario_kg_producto_precio_venta'),
        ('produccion', '0003_check_open_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='cantidad_producida',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='producto_terminado',
        ),
        migrations.CreateModel(
            name='SalidaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Cantidad')),
                ('precio_referencia', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio Referencia')),
                ('es_subproducto', models.BooleanField(default=False, verbose_name='Es Subproducto')),
                ('costo_asignado', models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=18, verbose_name='Costo Asignado')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='produccion.ordenproduccion', verbose_name='Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Salida de Orden',
                'verbose_name_plural': 'Salidas de Orden',
            },
        ),
    ]
