# Generated by Django 6.0.3 on 2026-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_remove_ordenproduccion_cantidad_producida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='kg_totales_salida',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=18, null=True, verbose_name='Kg Totales Salida'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='rendimiento_real',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=18, null=True, verbose_name='Rendimiento Real'),
        ),
        migrations.AddField(
            model_name='receta',
            name='unidad_rendimiento',
            field=models.CharField(default='L/Kg', max_length=20, verbose_name='Unidad de Rendimiento'),
        ),
    ]
