# Generated by Django 6.0.3 on 2026-03-15 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_ordenproduccion_kg_totales_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='produccion.ordenproduccion', verbose_name='Orden'),
        ),
    ]
