# Generated by Django 5.2.12 on 2026-04-03 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_fix_salidaorden_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccion',
            name='fecha_apertura',
            field=models.DateField(default=datetime.date.today, editable=False, verbose_name='Fecha de Apertura'),
        ),
    ]
