# Generated by Django 4.2.11 on 2026-04-04 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_alter_ordenproduccion_fecha_apertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccion',
            name='fecha_apertura',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Apertura'),
        ),
    ]
