# -*- coding: utf-8 -*-
# Generated by Django 6.0.3 on 2026-03-10 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='NÃºmero de Factura')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('APROBADA', 'Aprobada'), ('ANULADA', 'Anulada')], default='RECIBIDA', max_length=15, verbose_name='Estado')),
                ('moneda', models.CharField(choices=[('USD', 'USD - DÃ³lar Americano'), ('VES', 'VES - BolÃ\xadvar Soberano')], default='USD', max_length=3, verbose_name='Moneda')),
                ('tasa_cambio', models.DecimalField(decimal_places=6, default=1.0, max_digits=18, verbose_name='Tasa de Cambio (VES/USD)')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='Total (USD)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Factura de Compra',
                'verbose_name_plural': 'Facturas de Compra',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('rif', models.CharField(max_length=20, unique=True, verbose_name='RIF / IdentificaciÃ³n')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='TelÃ©fono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo ElectrÃ³nico')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Costo Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='Subtotal (USD)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.producto', verbose_name='Producto')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.facturacompra', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de Factura de Compra',
                'verbose_name_plural': 'Detalles de Facturas de Compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto del Pago (USD)')),
                ('medio_pago', models.CharField(choices=[('EFECTIVO_USD', 'Efectivo USD'), ('EFECTIVO_VES', 'Efectivo VES'), ('TRANSFERENCIA_USD', 'Transferencia USD'), ('TRANSFERENCIA_VES', 'Transferencia VES')], max_length=20, verbose_name='Medio de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='compras.facturacompra', verbose_name='Factura de Compra')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha', 'id'],
            },
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor', verbose_name='Proveedor'),
        ),
    ]
