# Generated by Django 6.0.3 on 2026-03-11 13:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cuenta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bancos.cuentabancaria', verbose_name='Cuenta Origen'),
        ),
        migrations.AddField(
            model_name='pago',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD - Dólar Americano'), ('VES', 'VES - Bolívar Soberano')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18, verbose_name='Monto en USD'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, verbose_name='Tasa de Cambio (VES/USD)'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD - Dólar Americano'), ('VES', 'VES - Bolívar Soberano')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='numero',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rif',
            field=models.CharField(max_length=20, unique=True, verbose_name='RIF / Identificación'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='GastoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Gasto')),
                ('categoria_gasto', models.CharField(choices=[('Electricidad', 'Electricidad'), ('Agua', 'Agua'), ('Gas', 'Gas'), ('Mantenimiento', 'Mantenimiento'), ('Transporte', 'Transporte'), ('Honorarios', 'Honorarios'), ('Otro', 'Otro')], max_length=25, verbose_name='Categoría de Gasto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('USD', 'USD - Dólar Americano'), ('VES', 'VES - Bolívar Soberano')], default='USD', max_length=3, verbose_name='Moneda')),
                ('tasa_cambio', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, verbose_name='Tasa de Cambio (VES/USD)')),
                ('monto_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18, verbose_name='Monto en USD')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('cuenta_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bancos.cuentabancaria', verbose_name='Cuenta de Pago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Gasto o Servicio',
                'verbose_name_plural': 'Gastos y Servicios',
                'ordering': ['-numero'],
            },
        ),
    ]
