# Generated by Django 6.0.3 on 2026-03-12 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_pago_cuenta_origen_pago_moneda_pago_monto_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='gastoservicio',
            name='fecha_emision',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Emisión'),
        ),
        migrations.AddField(
            model_name='gastoservicio',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
