# Generated by Django 6.0.3

from django.db import migrations

def create_categories_and_migrate(apps, schema_editor):
    CategoriaGasto = apps.get_model('core', 'CategoriaGasto')
    GastoServicio = apps.get_model('compras', 'GastoServicio')
    
    # Categorías FACTURA por defecto
    cats_factura = ['Electricidad', 'Agua', 'Gas', 'Mantenimiento', 'Transporte', 'Honorarios', 'Otro']
    
    cat_objs = {}
    for nombre in cats_factura:
        obj, created = CategoriaGasto.objects.get_or_create(
            nombre=nombre,
            contexto='FACTURA',
            defaults={'activa': True}
        )
        cat_objs[nombre] = obj
    
    # Migrar registros existentes
    for gasto in GastoServicio.objects.all():
        nombre_cat = gasto.categoria_gasto
        if nombre_cat in cat_objs:
            gasto.categoria_gasto = str(cat_objs[nombre_cat].id)
            gasto.save()
        else:
            gasto.categoria_gasto = str(cat_objs['Otro'].id)
            gasto.save()

def reverse_migrate(apps, schema_editor):
    # No es estrictamente necesario deshacer, pero podríamos intentar revertir los IDs a nombres
    # Sin embargo, revertir una migración que cambia tipos de datos es complejo.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_facturacompra_fecha_vencimiento_and_more'),
        ('core', '0005_tasacambio_categoriagasto'),
    ]

    operations = [
        migrations.RunPython(create_categories_and_migrate, reverse_migrate),
    ]
