# Generated by Django 6.0.3 on 2026-03-13 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_migrate_categories'),
        ('core', '0005_tasacambio_categoriagasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoservicio',
            name='categoria_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoriagasto', verbose_name='Categoría'),
        ),
    ]
