# Generated by Django 6.0.3 on 2026-03-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_gastoservicio_categoria_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número de Factura'),
        ),
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together={('proveedor', 'numero')},
        ),
    ]
