# Generated by Django 6.0.3 on 2026-03-16 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_facturacompra_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(blank=True, help_text='Para pago individual. Dejar vacío si es pago consolidado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='compras.facturacompra', verbose_name='Factura de Compra'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto'),
        ),
        migrations.CreateModel(
            name='DetallePagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Aplicado (USD)')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_pagos', to='compras.facturacompra', verbose_name='Factura')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_facturas', to='compras.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Detalle Pago - Factura',
                'verbose_name_plural': 'Detalles Pago - Facturas',
                'unique_together': {('pago', 'factura')},
            },
        ),
    ]
