# Generated by Django 6.0.3 on 2026-03-11 13:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Cuenta')),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta')),
                ('moneda', models.CharField(choices=[('USD', 'USD - Dólar Americano'), ('VES', 'VES - Bolívar Soberano')], default='USD', max_length=3, verbose_name='Moneda')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Saldo Actual')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('saldo_actual__gte', 0)), name='chk_saldo_positivo_cuenta')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFERENCIA_ENTRADA', 'Transferencia Entrada'), ('TRANSFERENCIA_SALIDA', 'Transferencia Salida'), ('REEXPRESION', 'Reexpresión')], max_length=25, verbose_name='Tipo de Movimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('USD', 'USD - Dólar Americano'), ('VES', 'VES - Bolívar Soberano')], max_length=3, verbose_name='Moneda')),
                ('tasa_cambio', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Tasa de Cambio (VES/USD)')),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto en USD')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.cuentabancaria', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Transferencia')),
                ('monto_origen', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Origen')),
                ('monto_destino', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Destino')),
                ('tasa_cambio', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, verbose_name='Tasa de Cambio')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EJECUTADA', 'Ejecutada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='bancos.cuentabancaria', verbose_name='Cuenta Destino')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origen', to='bancos.cuentabancaria', verbose_name='Cuenta Origen')),
            ],
            options={
                'verbose_name': 'Transferencia de Cuentas',
                'verbose_name_plural': 'Transferencias de Cuentas',
                'ordering': ['-fecha', '-numero'],
            },
        ),
    ]
