# Generated by Django 6.0.3 on 2026-03-13 18:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0002_periodoreexpresado'),
        ('core', '0005_tasacambio_categoriagasto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('tipo', models.CharField(choices=[('CARGO', 'Cargo'), ('ABONO', 'Abono')], max_length=10, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('USD', 'USD - Dólar Americano'), ('VES', 'VES - Bolívar Soberano')], max_length=3, verbose_name='Moneda')),
                ('tasa_cambio', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Tasa de Cambio (VES/USD)')),
                ('monto_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='Monto en USD')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoriagasto', verbose_name='Categoría')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_tesoreria', to='bancos.cuentabancaria', verbose_name='Cuenta')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Movimiento de Tesorería',
                'verbose_name_plural': 'Movimientos de Tesorería',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
