# Generated by Django 6.0.3 on 2026-03-14 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0003_movimientotesoreria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespaldoBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo', models.CharField(max_length=200)),
                ('tamanio_bytes', models.PositiveIntegerField(default=0)),
                ('exitoso', models.BooleanField(default=False)),
                ('error_mensaje', models.TextField(blank=True)),
                ('ejecutado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respaldo de BD',
                'verbose_name_plural': 'Respaldos de BD',
                'ordering': ['-fecha'],
            },
        ),
    ]
