# Generated by Django 6.0.3 on 2026-03-11 13:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_credito',
            field=models.PositiveIntegerField(default=30, verbose_name='Días de Crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_control_credito',
            field=models.CharField(choices=[('BLOQUEO', 'Bloqueo'), ('ADVERTENCIA', 'Advertencia')], default='ADVERTENCIA', max_length=15, verbose_name='Control de Crédito'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='cuenta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bancos.cuentabancaria', verbose_name='Cuenta Destino'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD - Dólar Americano'), ('VES', 'VES - Bolívar Soberano')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='monto_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18, verbose_name='Monto en USD'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18, verbose_name='Tasa de Cambio (VES/USD)'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Límite de Crédito (USD)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rif',
            field=models.CharField(max_length=20, unique=True, verbose_name='RIF / Identificación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD - Dólar Americano'), ('VES', 'VES - Bolívar Soberano')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='numero',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Factura'),
        ),
    ]
