# Generated by Django 6.0.3 on 2026-03-11 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_producto_peso_unitario_kg_producto_precio_venta'),
        ('ventas', '0002_cliente_dias_credito_cliente_tipo_control_credito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Lista')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('requiere_aprobacion', models.BooleanField(default=True, verbose_name='Requiere Aprobación')),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Listas de Precios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='detallefacturaventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=18, verbose_name='Precio Unitario'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='lista_precio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.listaprecio', verbose_name='Lista de Precios'),
        ),
        migrations.CreateModel(
            name='DetalleLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('vigente_desde', models.DateField(verbose_name='Vigente Desde')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.producto', verbose_name='Producto')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='ventas.listaprecio', verbose_name='Lista')),
            ],
            options={
                'verbose_name': 'Detalle de Lista de Precio',
                'verbose_name_plural': 'Detalles de Lista de Precio',
                'unique_together': {('lista', 'producto')},
            },
        ),
    ]
