# Generated by Django 6.0.3 on 2026-03-14 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_producto_es_materia_prima_base_producto_stock_maximo_and_more'),
        ('ventas', '0003_listaprecio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallelista',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios_en_tarifas', to='almacen.producto', verbose_name='Producto'),
        ),
    ]
