# Generated by Django 4.2.11 on 2026-04-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_cobro_monto_notacredito_detallenotacredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('COBRADA', 'Cobrada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15, verbose_name='Estado'),
        ),
    ]
